set-option -g status-position top

set -g allow-passthrough on
set -g set-clipboard on
set -g mouse on

set-option -g default-shell /bin/fish
set-option -a terminal-features 'xterm-256color:RGB'
set -as terminal-features ",*:hyperlinks"

# Set tmux to 1-based indexing
set -g base-index 1
setw -g pane-base-index 1

# Enable 256-color and truecolor rendering
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'

# Pane splits should open to the same path as the current pane
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

setenv -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins/"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'wfxr/tmux-power'

set -g @tmux_power_theme 'sky'
set -g @tmux_power_g0 "#090E13"
set -g @tmux_power_g2 "#090E13"
set -g @tmux_power_window_current_style   'none'
set -g @tmux_power_window_last_style	  'none'
set -g @tmux_power_window_activity_style  'none'
set -g @tmux_power_window_bell_style      'none'
set -g @tmux_power_prefix_highlight_style 'none'
set -g @tmux_power_left_a ''

# Plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

set -g @plugin 'tmux-plugins/tmux-yank'

# for vim
set -g @resurrect-strategy-vim 'session'
# for neovim
set -g @resurrect-strategy-nvim 'session'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g window-status-format "#[fg=#090E13,bg=#090E13]#[fg=#87ceeb,bg=#090E13] #I • #W #[fg=#090E13,bg=#090E13]"
set -g window-status-current-format "#[fg=#090E13,bg=#87ceeb]#[fg=#262626,bg=#87ceeb,none] #I • #W #[fg=#87ceeb,bg=#090E13,none]"
